
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.appendChild(e);setTimeout(()=>e.remove(),1500)}
function get(k){try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}}function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function moneyToNumber(v){const n=parseFloat(String(v||'0').replace(/[^0-9.]/g,''));return isNaN(n)?0:n}
function changeQty(d){const i=document.getElementById('qtyInput');if(!i)return;let v=parseInt(i.value||'1',10);if(isNaN(v))v=1;i.value=Math.max(1,v+d)}
function switchMainImage(src,btn){const img=document.getElementById('mainProductImage');if(img)img.src=src;document.querySelectorAll('.thumb').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active')}
function addToCart(slug,title,img,sku,asin,price){const q=Math.max(1,parseInt((document.getElementById('qtyInput')||{}).value||'1',10)||1);const a=get('cart');const f=a.find(x=>x.slug===slug);if(f)f.qty+=q;else a.push({slug,title,img,sku,asin,price,qty:q});set('cart',a);toast('Added to cart');setTimeout(()=>location.href='/cart.html',350)}
function addWishlist(slug,title,img,sku,asin){let a=get('wishlist');if(!a.find(x=>x.slug===slug))a.push({slug,title,img,sku,asin});set('wishlist',a);toast('Wishlist updated');setTimeout(()=>location.href='/wishlist.html',350)}
function addCompare(slug,title,img,sku,asin,category){let a=get('compare');if(!a.find(x=>x.slug===slug))a.push({slug,title,img,sku,asin,category});set('compare',a);toast('Compare updated');setTimeout(()=>location.href='/compare.html',350)}
function renderCart(){const root=document.getElementById('cart-page');if(!root)return;const a=get('cart');if(!a.length){root.innerHTML='<div class="empty-box">Your cart is empty. <a href="/products.html">Shop products</a></div>';return;}root.innerHTML='<div class="cart-list">'+a.map((x,i)=>`<div class="cart-row"><img src="${x.img||'/main.svg'}" onerror="this.src='/main.svg'"><div class="cart-info"><b>${x.title||''}</b><span>SKU: ${x.sku||''} | ASIN: ${x.asin||''}</span><em>${x.price||'$199.99'}</em></div><div class="cart-qty">Qty: ${x.qty||1}</div><a class="view-link" href="/${x.slug}.html">View Product</a><button class="remove-btn" onclick="removeItem('cart',${i})">×</button></div>`).join('')+'</div>'}
function renderList(id,key,empty){const root=document.getElementById(id);if(!root)return;const a=get(key);if(!a.length){root.innerHTML='<div class="empty-box">'+empty+'</div>';return;}root.innerHTML='<table class="table-list"><tbody>'+a.map((x,i)=>`<tr><td><img src="${x.img||'/main.svg'}" onerror="this.src='/main.svg'"></td><td><b>${x.title||''}</b><br><span style="color:#64748b">SKU: ${x.sku||''} | ASIN: ${x.asin||''}</span></td><td><a href="/${x.slug}.html">View Product</a></td><td><button class="remove-btn" onclick="removeItem('${key}',${i})">×</button></td></tr>`).join('')+'</tbody></table>'}
function removeItem(key,i){const a=get(key);a.splice(i,1);set(key,a);renderCart();renderList('wishlist-page','wishlist','Your wishlist is empty.');renderList('compare-page','compare','No products selected.');renderCheckoutSummary();renderCheckoutItems()}
function renderCheckoutItems(){const root=document.getElementById('checkout-items');if(!root)return;const items=get('cart');if(!items.length){root.innerHTML='<div class="empty-box">Your cart is empty.</div>';return;}root.innerHTML=items.map(x=>`<div class="checkout-item"><img src="${x.img||'/main.svg'}" onerror="this.src='/main.svg'"><div><b>${x.title||''}</b><span>SKU: ${x.sku||''} | ASIN: ${x.asin||''}</span><em>Qty: ${x.qty||1}</em></div><strong>${x.price||'$199.99'}</strong></div>`).join('')}
function renderCheckoutSummary(){const root=document.getElementById('checkout-summary');if(!root)return;const items=get('cart');if(!items.length){root.innerHTML='<div class="empty-box">Your cart is empty.</div>';return;}let subtotal=0,qty=0;items.forEach(x=>{const q=parseInt(x.qty||1,10)||1;qty+=q;subtotal+=moneyToNumber(x.price||'$199.99')*q});root.innerHTML=`<div class="summary-lines"><p><span>Items (${qty})</span><b>$${subtotal.toFixed(2)}</b></p><p><span>Shipping & handling</span><b>$0.00</b></p><p><span>Estimated tax</span><b>$0.00</b></p><p class="summary-total"><span>Order total</span><b>$${subtotal.toFixed(2)}</b></p></div>`}
function placeDemoOrder(){const items=get('cart');const msg=document.getElementById('order-message');if(!msg)return;if(!items.length){msg.innerHTML='<div class="order-error">Your cart is empty.</div>';return;}const name=(document.getElementById('checkoutName')||{}).value||'';const email=(document.getElementById('checkoutEmail')||{}).value||'';if(!name.trim()||!email.trim()){msg.innerHTML='<div class="order-error">Please enter your name and email.</div>';return;}const orderId='AF-'+Date.now().toString().slice(-8);msg.innerHTML=`<div class="order-success"><h2>Order Submitted</h2><p>Order reference: <b>${orderId}</b></p><p>Customer service will confirm the order by email.</p></div>`}
document.addEventListener('DOMContentLoaded',()=>{renderCart();renderList('wishlist-page','wishlist','Your wishlist is empty.');renderList('compare-page','compare','No products selected.');renderCheckoutSummary();renderCheckoutItems();const params=new URLSearchParams(location.search);const q=(params.get('q')||'').toLowerCase();const c=params.get('category')||'';document.querySelectorAll('#static-product-grid .product-card').forEach(card=>{const show=(!q||(card.dataset.title+' '+card.dataset.asin+' '+card.dataset.sku).includes(q))&&(!c||card.dataset.category===c);card.style.display=show?'':'none'})});
